
general:
  seed: 7
  data_dir: data
  logs_dir: logs
  temp_dir: tmp
  models_dir: models

experiment:
  load_pretrained: False
  model_name: Test            # the name of the pre-trained model, or if load_pretrained is False -- the name of the new model
  dataset: mnist

training:
  optimiser: adam
  learning_rate: 1e-3
  decay_per_epoch: none





